# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/app.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/app.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10protos/app.proto\".\n\x0cLoginRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"@\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\"\x07\n\x05\x45mpty\"+\n\x15GetCategoriesResponse\x12\x12\n\ncategories\x18\x01 \x03(\t\"v\n\x11\x41\x64\x64ProductRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x10\n\x08quantity\x18\x04 \x01(\x05\x12\x11\n\tproductId\x18\x05 \x01(\t\x12\r\n\x05image\x18\x06 \x01(\x0c\"%\n\x12\x41\x64\x64ProductResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"h\n\x14UpdateProductRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12!\n\toperation\x18\x04 \x01(\x0e\x32\x0e.OperationType\"(\n\x15UpdateProductResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"?\n\x1cGetProductsByCategoryRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"~\n\x07Product\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x10\n\x08quantity\x18\x04 \x01(\x05\x12\x11\n\tproductId\x18\x05 \x01(\t\x12\r\n\x05image\x18\x06 \x01(\x0c\x12\x10\n\x08imageUrl\x18\x07 \x01(\t\";\n\x1dGetProductsByCategoryResponse\x12\x1a\n\x08products\x18\x01 \x03(\x0b\x32\x08.Product*\'\n\rOperationType\x12\n\n\x06UPDATE\x10\x00\x12\n\n\x06\x44\x45LETE\x10\x01\x32\xb8\x02\n\x0eproductService\x12&\n\x05login\x12\r.LoginRequest\x1a\x0e.LoginResponse\x12/\n\rGetCategories\x12\x06.Empty\x1a\x16.GetCategoriesResponse\x12\x35\n\naddProduct\x12\x12.AddProductRequest\x1a\x13.AddProductResponse\x12>\n\rupdateProduct\x12\x15.UpdateProductRequest\x1a\x16.UpdateProductResponse\x12V\n\x15GetProductsByCategory\x12\x1d.GetProductsByCategoryRequest\x1a\x1e.GetProductsByCategoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.app_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERATIONTYPE']._serialized_start=749
  _globals['_OPERATIONTYPE']._serialized_end=788
  _globals['_LOGINREQUEST']._serialized_start=20
  _globals['_LOGINREQUEST']._serialized_end=66
  _globals['_LOGINRESPONSE']._serialized_start=68
  _globals['_LOGINRESPONSE']._serialized_end=132
  _globals['_EMPTY']._serialized_start=134
  _globals['_EMPTY']._serialized_end=141
  _globals['_GETCATEGORIESRESPONSE']._serialized_start=143
  _globals['_GETCATEGORIESRESPONSE']._serialized_end=186
  _globals['_ADDPRODUCTREQUEST']._serialized_start=188
  _globals['_ADDPRODUCTREQUEST']._serialized_end=306
  _globals['_ADDPRODUCTRESPONSE']._serialized_start=308
  _globals['_ADDPRODUCTRESPONSE']._serialized_end=345
  _globals['_UPDATEPRODUCTREQUEST']._serialized_start=347
  _globals['_UPDATEPRODUCTREQUEST']._serialized_end=451
  _globals['_UPDATEPRODUCTRESPONSE']._serialized_start=453
  _globals['_UPDATEPRODUCTRESPONSE']._serialized_end=493
  _globals['_GETPRODUCTSBYCATEGORYREQUEST']._serialized_start=495
  _globals['_GETPRODUCTSBYCATEGORYREQUEST']._serialized_end=558
  _globals['_PRODUCT']._serialized_start=560
  _globals['_PRODUCT']._serialized_end=686
  _globals['_GETPRODUCTSBYCATEGORYRESPONSE']._serialized_start=688
  _globals['_GETPRODUCTSBYCATEGORYRESPONSE']._serialized_end=747
  _globals['_PRODUCTSERVICE']._serialized_start=791
  _globals['_PRODUCTSERVICE']._serialized_end=1103
# @@protoc_insertion_point(module_scope)
